name: Build Manager

on:
  push:
    branches: [ "main", "ci" ]
    paths:
      - '.github/workflows/build-manager-common.yml'
      - '.github/workflows/ksud.yml'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/ksud/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'manager/**'
  workflow_call:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager-common.yml
    secrets: inherit
    with:
      spoofed: false
