name: Release ksud

on:
 workflow_dispatch:
 
jobs:
  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit

  build-ksud:
    needs: build-lkm
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
          - target: x86_64-linux-android
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu # windows pc
            os: ubuntu-latest
          - target: x86_64-apple-darwin # Intel mac
            os: macos-latest
          - target: aarch64-apple-darwin # M chip mac
            os: macos-latest
          - target: aarch64-unknown-linux-musl # arm64 Linux
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl # x86 Linux
            os: ubuntu-latest
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}  
  release:
    needs: build-ksud
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
          - target: x86_64-linux-android
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu # windows pc
            os: ubuntu-latest
          - target: x86_64-apple-darwin # Intel mac
            os: macos-latest
          - target: aarch64-apple-darwin # M chip mac
            os: macos-latest
          - target: aarch64-unknown-linux-musl # arm64 Linux
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl # x86 Linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Current Time
        run: |
          TIME=$(date +"%Y-%m-%d-%H.%M")
          echo "TIME=$TIME" >> $GITHUB_ENV
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
            name: ksud-${{ matrix.target }}
      - name: Package (${{ matrix.target }})
        run: |
         7z a -tzip ksud-${{ matrix.target }}.zip ./ksud-${{ matrix.target }}/release
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.4
        with:
            tag_name: 'ksud-${{ env.TIME }}'
            files: ./**/ksud-*.zip