name: Release

on:
 workflow_dispatch:
 
jobs:
  Build:
    uses: ./.github/workflows/build-manager.yml
  release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
      - name: Create Release
        uses: softprops/action-gh-release@v2.0.4
        with:
            files: ./**/*.*