name: Rustfmt check

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud/**'

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - uses: dtolnay/rust-toolchain@v1
        with:
          components: rustfmt

      - uses: LoliGothick/rustfmt-check@v0.4.2
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksud
